name: Unit tests

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - composer.json
      - composer.lock
      - src/**
      - ftests/**
      - tests/**

jobs:
  phpunit:
    strategy:
      matrix:
        guzzle: ["<= 6.5.5", "<= 7.4.2"]
        monolog: ["<= 1.27.0", "<= 2.3.5"]
        mail-mime-parser: ["<= 1.3.3", "<= 2.2.1"]
        nuxeo: ["9.10"]
        php: ["7.2", "7.3"]
    runs-on: ubuntu-latest
    services:
      nuxeo:
        image: "nuxeo:${{ matrix.nuxeo }}"
        ports:
          - 8080:8080
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
          tools: composer
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: composer install
      - run: composer update -W "guzzlehttp/guzzle:${{ matrix.guzzle }}" "monolog/monolog:${{ matrix.monolog }}" "zbateson/mail-mime-parser:${{ matrix.mail-mime-parser }}"
      - run: |
          vendor/bin/phpunit \
            --coverage-clover target/phpunit.coverage.xml \
            --log-junit target/phpunit.report.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./target/phpunit.coverage.xml
          flags: unit
          env_vars: PHP